name: commit_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: abystoma/external-workflow
      - name: Greetings
        run: echo "$(<greeting.txt)"
